# Generated by Django 3.2.8 on 2022-03-09 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('display_images', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=2000)),
            ],
        ),
    ]
