# Generated by Django 3.2.8 on 2022-03-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='title',
            new_name='n_title',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='url',
            new_name='n_url',
        ),
    ]
