# Generated by Django 3.2.8 on 2021-10-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plants_display_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='display_images',
            field=models.ImageField(blank=True, default='default_images', upload_to=''),
        ),
    ]
