# Generated by Django 3.2.8 on 2021-10-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_plants_display_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
