# Generated by Django 3.2.8 on 2021-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plants_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='default_images', upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('disease', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
