# Generated by Django 3.2.8 on 2022-03-09 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_predict'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('images', models.ImageField(blank=True, default='default_images', upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('urlField', models.URLField(max_length=250)),
            ],
        ),
    ]
